---
server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
apiCredentials:
  admin: password
# uncomment and modify as necessary to enable redis storage
#storage:
#  factoryClass: mck.service.urlalias.storage.redis.RedisUrlAliasStorageFactory
#  factory:
#    redis:
#      host: localhost
#      port: 6379
#      ssl: false
