apiVersion: v1
kind: ConfigMap
metadata:
  name: aka
data:
  configuration.yaml: |
    ---
    apiCredentials:
      admin: "password"
    storage:
      factoryClass: mck.service.aka.storage.redis.RedisUrlAliasStorageFactory
      factory:
        redis:
          host: redis
          port: 6379
          ssl: false
